# Generated by Django 2.2.4 on 2020-02-02 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideus', '0004_auto_20200202_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.IntegerField(choices=[(2, '디자인'), (0, '기타'), (1, '코딩'), (3, '교육')], default=0),
        ),
    ]
