# Generated by Django 2.2.4 on 2020-02-02 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideus', '0005_auto_20200202_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.IntegerField(choices=[(3, '교육'), (0, '기타'), (1, '코딩'), (2, '디자인')], default=0),
        ),
    ]
